# https://docs.docker.com/compose/environment-variables/envvars-precedence/
# Environment leverage the gerarchy defined in the docker compose between "env_file" and "environment" attributes
# ecosystem variables defined in the "env_file" .env.${GUARDIAN_ENV}.guardian.system
# specific service variables defined by "environment" can override what is defined in the ecosystem file
services:
    mongo:
        image: mongo:6.0.15
        command: "--setParameter allowDiskUseByDefault=true"
        expose:
            - 27017
    
    mongo-express:
        image: mongo-express:1.0.2-20
        expose:
            - 8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_SITE_BASEURL: /mongo-admin # default credentials: admin/pass
        depends_on:
                - mongo

    cache:
        image: registry.redict.io/redict:7.3.0
        platform: linux/amd64
        expose:
            - 6379

    ipfs-node:
        image: ipfs/kubo:v0.29.0
        ports:
            - "5001:5001"
            - "4001:4001"
            - "8080:8080"
        volumes:
            - ipfs_data:/data/ipfs:rw
            - ipfs_export:/export:rw

    message-broker:
        image: nats:2.9.24
        expose:
            - 4222
        ports:
            - "8222:8222"
        command: "--http_port 8222"

    notification-service:
        image: gcr.io/hedera-registry/notification-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./notification-service/Dockerfile
        init: true
        depends_on:
            - message-broker
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        volumes:
            - ./notification-service/configs:/usr/local/notification-service/configs:ro

    logger-service:
        image: gcr.io/hedera-registry/logger-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./logger-service/Dockerfile
        init: true
        depends_on:
            - message-broker
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        expose:
            - 6555
        volumes:
            - ./logger-service/configs:/usr/local/logger-service/configs:ro

    queue-service:
        image: gcr.io/hedera-registry/queue-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./queue-service/Dockerfile
        init: true
        depends_on:
            - mongo
            - message-broker
            - logger-service
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        expose:
            - 6555

    worker-service:
        image: gcr.io/hedera-registry/worker-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./worker-service/Dockerfile
        init: true
        depends_on:
            queue-service:
                condition: service_started
            ipfs-node:
                condition: service_healthy
            auth-service:
                condition: service_started
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        expose:
            - 6555
        volumes:
            - ./worker-service/tls:/usr/local/worker-service/tls:ro
            - ./worker-service/configs:/usr/local/worker-service/configs:ro
        deploy:
            replicas: 1

    auth-service:
        image: gcr.io/hedera-registry/auth-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./auth-service/Dockerfile.demo
        init: true
        ports:
            - "5005:5005"
        volumes:
            - ./auth-service/tls:/usr/local/auth-service/tls:ro
            - ./auth-service/configs:/usr/local/auth-service/configs:ro
        depends_on:
            - mongo
            - message-broker
            - logger-service
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        expose:
            - 6555
            - 5005

    api-gateway:
        image: gcr.io/hedera-registry/api-gateway:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./api-gateway/Dockerfile.demo
        init: true
        expose:
            - 3002
            - 6555
        depends_on:
            - mongo
            - cache
            - message-broker
            - guardian-service
            - auth-service
            - logger-service
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        volumes:
            - ./api-gateway/configs:/usr/local/api-gateway/configs:ro

    policy-service:
        image: gcr.io/hedera-registry/policy-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./policy-service/Dockerfile
        init: true
        ports:
            - "5006:5006"
        depends_on:
            - mongo
            - message-broker
            - auth-service
            - logger-service
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        expose:
            - 50000-60000
            - 5006
        volumes:
            - ./policy-service/tls:/usr/local/policy-service/tls:ro
            - ./policy-service/configs:/usr/local/policy-service/configs:ro

    guardian-service:
        image: gcr.io/hedera-registry/guardian-service:2.27.1
        platform: linux/amd64
        env_file:
            - ./configs/.env.${GUARDIAN_ENV}.guardian.system
        build:
            context: .
            dockerfile: ./guardian-service/Dockerfile
        init: true
        ports:
            - "5007:5007"
        volumes:
            - ./guardian-service/tls:/usr/local/guardian-service/tls:ro
            - ./guardian-service/configs:/usr/local/guardian-service/configs:ro
        depends_on:
            - mongo
            - message-broker
            - auth-service
            - logger-service
            - worker-service
            - policy-service
        environment:
            - GUARDIAN_ENV=${GUARDIAN_ENV}
        expose:
            - 6555
            - 5007

    mrv-sender:
        build:
            context: .
            dockerfile: ./mrv-sender/Dockerfile
        init: true
        ports:
            - "5008:5008"
        expose:
            - 3005
            - 5008

    web-proxy:
        build:
            context: .
            dockerfile: ./web-proxy/Dockerfile.demo
        init: true
        environment:
            GATEWAY_CLIENT_MAX_BODY_SIZE: 1024m
            GATEWAY_HOST: api-gateway
            GATEWAY_PORT: 3002
            MRV_SENDER_HOST: mrv-sender
            MRV_SENDER_PORT: 3005
            TOPIC_VIEWER_HOST: topic-viewer
            TOPIC_VIEWER_PORT: 3006
        ports:
            - "3000:80"
        depends_on:
            - guardian-service
            - auth-service
            - api-gateway

volumes:
    ipfs_data:
    ipfs_export:

networks:
    monitoring:
        driver: bridge
